### ISSUE TITLE
Toggle Button

### ISSUE THREAD

**Issue by ShoulderKarlsson** [ntwigs/Let-it-snow#3]
I am still not pleased with the button

**Comment by ntwigs** [comment]
Sit down in the boad

**Comment by ShoulderKarlsson** [comment]
![dsc02339](https://cloud.githubusercontent.com/assets/14080808/21313780/1794872a-c5f4-11e6-9936-b00a864baef0.JPG)

**Comment by ShoulderKarlsson** [comment]
![images](https://cloud.githubusercontent.com/assets/14080808/21313791/29414abc-c5f4-11e6-8068-13ef6575dbc5.jpeg)
